
name: Build and Deploy Spring Project

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: Build the Application
        run: 
              mvn clean
               mvn -B package -f SPRING_PROJECT/pom.xml-x
      - name: Unit Test
        run: mvn -B test -f SPRING_PROJECT/pom.xml-x

      

      - name: Echo Message
        run: echo "This is my first pipeline."
